In [1]:
import pandas as pd

In [2]:
import os

In [3]:
import pickle

In [4]:
DATASET_PATH = "../datasets/supplement_dataset"
MODEL_PATH = "../models/supplement"

model_path = os.path.join(MODEL_PATH, "supplement_model.pkl")
supplements_path = os.path.join(DATASET_PATH, "supplements_sri_lankan_prices.csv")
interactions_path = os.path.join(DATASET_PATH, "interactions.csv")

In [5]:
with open(model_path, "rb") as f:
    model = pickle.load(f)

supplements_df = pd.read_csv(supplements_path)
interactions_df = pd.read_csv(interactions_path)

print("Model and datasets loaded successfully!")
print("Supplements:", supplements_df.shape)
print("Interactions:", interactions_df.shape)

Model and datasets loaded successfully!
Supplements: (3000, 19)
Interactions: (3000, 6)

In [6]:
sample_user = pd.DataFrame([{
    "age": 24,
    "gender": "female",
    "height_cm": 160,
    "weight_kg": 55,
    "bmi": 21.5,
    "health_condition": "none",
    "medication": "none",
    "goal": "muscle gain",
    "budget_range": "10000-25000",
    "activity_level": "moderate"
}])

In [7]:
predicted_category = model.predict(sample_user)[0]

print("Predicted Category:", predicted_category)

Predicted Category: protein

In [8]:
supplements_df.columns.tolist()

['supplement_id',
 'name',
 'category',
 'target_goal',
 'ingredients',
 'dosage',
 'price_range',
 'brand',
 'size',
 'form',
 'price_lkr',
 'price_range_lkr',
 'currency',
 'store_name',
 'price_source',
 'last_checked',
 'data_type',
 'price_note',
 'rating']

In [9]:
# Normalize text columns
text_cols = ["category", "price_range_lkr", "ingredients", "brand", "name", "target_goal"]

for col in text_cols:
    if col in supplements_df.columns:
        supplements_df[col] = supplements_df[col].astype(str).str.strip().str.lower()

predicted_category = str(predicted_category).strip().lower()
user_budget = str(sample_user.loc[0, "budget_range"]).strip().lower()

print("Predicted Category:", predicted_category)
print("User Budget:", user_budget)

Predicted Category: protein
User Budget: 10000-25000

In [10]:
recommended_products = supplements_df[
    (supplements_df["category"] == predicted_category) &
    (supplements_df["price_range_lkr"] == user_budget)
]

print("Recommended products count:", len(recommended_products))

recommended_products.head(10)

Recommended products count: 199

,supplement_id,name,category,target_goal,ingredients,dosage,price_range,brand,size,form,price_lkr,price_range_lkr,currency,store_name,price_source,last_checked,data_type,price_note,rating
8,S0009,stronglife collagen peptides ultra,protein,general wellness,collagen peptides; vitamin c,1 scoop daily,High,generic sports nutrition,2lb-5lb,powder,17500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.6
33,S0034,nutrimax collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,1 scoop daily,High,rule 1,2lb-5lb,powder,19500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.3
53,S0054,optiwell collagen peptides plus,protein,endurance,collagen peptides; vitamin c,1 scoop daily,High,dymatize,2lb-5lb,powder,17500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.3
59,S0060,wellgen collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,1 scoop daily,High,mutant,2lb-5lb,powder,19500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.1
68,S0069,nutrimax whey protein basic,protein,immunity,whey protein isolate; branched-chain amino acids,1 scoop after workout,Medium,muscletech,2lb-5lb,powder,18500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.6
95,S0096,fitcore whey protein,protein,muscle gain,whey protein isolate; branched-chain amino acids,1 scoop after workout,Medium,dymatize,2lb-5lb,powder,18500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.5
100,S0101,ceyfit collagen peptides advanced,protein,hair and skin,collagen peptides; vitamin c,1 scoop daily,High,mutant,2lb-5lb,powder,12500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,3.9
101,S0102,stronglife collagen peptides basic,protein,arm muscle growth,collagen peptides; vitamin c,1 scoop daily,Low,applied nutrition,2lb-5lb,powder,22500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.2
111,S0112,healthplus collagen peptides advanced,protein,energy boost,collagen peptides; vitamin c,1 scoop daily,High,mutant,2lb-5lb,powder,22500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.5
112,S0113,nutrimax collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,1 scoop daily,High,generic sports nutrition,2lb-5lb,powder,17500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.1

In [11]:
final_recommendations = recommended_products.head(5)

final_recommendations[
    [
        "supplement_id",
        "name",
        "category",
        "target_goal",
        "ingredients",
        "price_lkr",
        "price_range_lkr",
        "brand",
        "rating"
    ]
]

,supplement_id,name,category,target_goal,ingredients,price_lkr,price_range_lkr,brand,rating
8,S0009,stronglife collagen peptides ultra,protein,general wellness,collagen peptides; vitamin c,17500,10000-25000,generic sports nutrition,4.6
33,S0034,nutrimax collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,19500,10000-25000,rule 1,4.3
53,S0054,optiwell collagen peptides plus,protein,endurance,collagen peptides; vitamin c,17500,10000-25000,dymatize,4.3
59,S0060,wellgen collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,19500,10000-25000,mutant,4.1
68,S0069,nutrimax whey protein basic,protein,immunity,whey protein isolate; branched-chain amino acids,18500,10000-25000,muscletech,4.6

In [12]:
interactions_df.columns.tolist()

['interaction_id',
 'medicine',
 'supplement_ingredient',
 'interaction_risk',
 'severity',
 'recommendation']

In [13]:
# Normalize interaction dataset text columns
for col in interactions_df.columns:
    if interactions_df[col].dtype == "object":
        interactions_df[col] = interactions_df[col].astype(str).str.strip().str.lower()

interactions_df.head()

,interaction_id,medicine,supplement_ingredient,interaction_risk,severity,recommendation
0,I0001,Warfarin,omega-3 EPA DHA,Bleeding risk may increase,High,Avoid or consult healthcare professional
1,I0002,Warfarin,curcumin,Bleeding risk may increase,High,Avoid or consult healthcare professional
2,I0003,Warfarin,green tea extract,May affect anticoagulant control,Moderate,Use only with professional advice
3,I0004,Aspirin,omega-3 EPA DHA,Bleeding risk may increase,Moderate,Monitor and consult healthcare professional
4,I0005,Clopidogrel,curcumin,Bleeding risk may increase,High,Avoid or consult healthcare professional

In [14]:
def check_supplement_safety(recommended_products, user_medications, interactions_df):
    safe_products = []
    unsafe_products = []

    # user medications normalize
    user_medications = [str(med).strip().lower() for med in user_medications]

    for _, product in recommended_products.iterrows():
        product_ingredients = str(product.get("ingredients", "")).lower()
        product_name = product.get("name", "unknown product")

        product_warnings = []

        for med in user_medications:
            if med in ["none", "no", "nan", ""]:
                continue

            # Find interaction rules for this medication
            med_rules = interactions_df[
                interactions_df["medicine"].str.contains(med, case=False, na=False)
            ]

            for _, rule in med_rules.iterrows():
                risky_ingredient = str(rule["supplement_ingredient"]).lower()

                # Check if risky ingredient exists in product ingredients
                if risky_ingredient in product_ingredients:
                    product_warnings.append({
                        "medicine": rule["medicine"],
                        "supplement_ingredient": rule["supplement_ingredient"],
                        "interaction_risk": rule["interaction_risk"],
                        "severity": rule["severity"],
                        "recommendation": rule["recommendation"]
                    })

        if product_warnings:
            unsafe_products.append({
                "supplement_id": product.get("supplement_id"),
                "name": product_name,
                "category": product.get("category"),
                "price_lkr": product.get("price_lkr"),
                "warnings": product_warnings
            })
        else:
            safe_products.append(product)

    safe_products_df = pd.DataFrame(safe_products)

    return safe_products_df, unsafe_products

In [15]:
user_medications = ["none"]

safe_products_df, unsafe_products = check_supplement_safety(
    recommended_products,
    user_medications,
    interactions_df
)

print("Safe products:", len(safe_products_df))
print("Unsafe products:", len(unsafe_products))

safe_products_df.head(5)

Safe products: 199
Unsafe products: 0

,supplement_id,name,category,target_goal,ingredients,dosage,price_range,brand,size,form,price_lkr,price_range_lkr,currency,store_name,price_source,last_checked,data_type,price_note,rating
8,S0009,stronglife collagen peptides ultra,protein,general wellness,collagen peptides; vitamin c,1 scoop daily,High,generic sports nutrition,2lb-5lb,powder,17500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.6
33,S0034,nutrimax collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,1 scoop daily,High,rule 1,2lb-5lb,powder,19500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.3
53,S0054,optiwell collagen peptides plus,protein,endurance,collagen peptides; vitamin c,1 scoop daily,High,dymatize,2lb-5lb,powder,17500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.3
59,S0060,wellgen collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,1 scoop daily,High,mutant,2lb-5lb,powder,19500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.1
68,S0069,nutrimax whey protein basic,protein,immunity,whey protein isolate; branched-chain amino acids,1 scoop after workout,Medium,muscletech,2lb-5lb,powder,18500,10000-25000,LKR,Sri Lankan Supplement Market,Estimated from Sri Lankan online supplement st...,2026-05-06,synthetic_with_sri_lankan_price_estimate,Prototype estimate; verify exact live price be...,4.6

In [16]:
user_medications = ["warfarin"]

safe_products_df, unsafe_products = check_supplement_safety(
    recommended_products,
    user_medications,
    interactions_df
)

print("Safe products:", len(safe_products_df))
print("Unsafe products:", len(unsafe_products))

unsafe_products

Safe products: 116
Unsafe products: 83

[{'supplement_id': 'S0069',
  'name': 'nutrimax whey protein basic',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0096',
  'name': 'fitcore whey protein',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0204',
  'name': 'vitalab casein protein basic',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0215',
  'name': 'activefuel whey protein basic',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0250',
  'name': 'bioactive casein protein advanced',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0336',
  'name': 'wellgen casein protein',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0339',
  'name': 'pronutra casein protein pro',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0367',
  'name': 'wellgen whey protein',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0398',
  'name': 'vitalab whey protein advanced',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0403',
  'name': 'bioactive whey protein plus',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0468',
  'name': 'pronutra casein protein plus',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0516',
  'name': 'healthplus whey protein basic',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0521',
  'name': 'stronglife whey protein pro',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0547',
  'name': 'vitalab casein protein plus',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0554',
  'name': 'healthplus whey protein pro',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0555',
  'name': 'pronutra whey protein',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0618',
  'name': 'bioactive whey protein basic',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0633',
  'name': 'activefuel casein protein',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0645',
  'name': 'healthplus whey protein ultra',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0682',
  'name': 'ceyfit whey protein advanced',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0686',
  'name': 'activefuel whey protein ultra',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0746',
  'name': 'pureform whey protein ultra',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0761',
  'name': 'fitcore whey protein basic',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0775',
  'name': 'vitalab whey protein plus',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0785',
  'name': 'activefuel whey protein pro',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0799',
  'name': 'fitcore casein protein ultra',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0812',
  'name': 'nutrimax whey protein basic',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0842',
  'name': 'activefuel whey protein advanced',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0843',
  'name': 'vitalab whey protein basic',
  'category': 'protein',
  'price_lkr': 18500,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0874',
  'name': 'bioactive whey protein plus',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0910',
  'name': 'activefuel casein protein',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'casein protein',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'}]},
 {'supplement_id': 'S0944',
  'name': 'bioactive whey protein pro',
  'category': 'protein',
  'price_lkr': 22000,
  'warnings': [{'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',
    'recommendation': 'Monitor symptoms and follow label instructions'},
   {'medicine': 'Warfarin',
    'supplement_ingredient': 'branched-chain amino acids',
    'interaction_risk': 'Possible mild interaction or timing issue',
    'severity': 'Low',

In [17]:
final_safe_recommendations = safe_products_df.head(5)

final_safe_recommendations[
    [
        "supplement_id",
        "name",
        "category",
        "target_goal",
        "ingredients",
        "price_lkr",
        "price_range_lkr",
        "brand",
        "rating"
    ]
]

,supplement_id,name,category,target_goal,ingredients,price_lkr,price_range_lkr,brand,rating
8,S0009,stronglife collagen peptides ultra,protein,general wellness,collagen peptides; vitamin c,17500,10000-25000,generic sports nutrition,4.6
33,S0034,nutrimax collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,19500,10000-25000,rule 1,4.3
53,S0054,optiwell collagen peptides plus,protein,endurance,collagen peptides; vitamin c,17500,10000-25000,dymatize,4.3
59,S0060,wellgen collagen peptides ultra,protein,hair and skin,collagen peptides; vitamin c,19500,10000-25000,mutant,4.1
100,S0101,ceyfit collagen peptides advanced,protein,hair and skin,collagen peptides; vitamin c,12500,10000-25000,mutant,3.9